//theme development
var stories2 = [
    {
        "itemName": "Public Housing Developments Displace Residents",
        "itemSubhead": "Neighborhoods Identified as “Slums” Demolished to Make Way for new Developments",
        "itemDescription": "Thousands of Black residents were displaced when the Atlanta Housing Authority started building public housing in the mid-1930s. As in virtually all American cities at the time, these housing projects were racially segregated, formally in the South but informally in the North prior to 1964.  Not all of the housing destroyed fit the description of “slums” that was used to justify these projects. This man, moving his family’s belongings prior to the opening of the Alonzo Herndon Homes in 1941, may have hauled ice for a living, small-scale entrepreneurship being a strategy some Black men successfully used to avoid racial discrimination in the workplace.  Black homeowners in the demolished areas typically did not receive fair market value for their homes, and faced the predicament of finding new housing in a segregated market with many areas off-limits to them.",
        "itemMedia":'<img class="content" src="images/05.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/05.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Schisms Between Civil Rights Movement Groups Rise in the Mid-Late 60’s",
        "itemSubhead": "Multiple Community Development, Civil Rights and Black Power activist groups in Vine City in the 1960’s and 70’s.",
        "itemDescription": "In the mid-1960’s not only were leaders from the Southern Christian Leadership Council (SCLC) and the Student Nonviolent Coordinating Committee (SNCC) active in the community, but area colleges and universities and early public-private initiatives such as the Council on Human Relations of Greater Atlanta, Inc. spearheaded projects as well. An example of such a project is the “Vine City Project: Experiments in Self Help” which paired area college students with community members to work on cleanup projects and other “experiments” in community self directed development. Seen by many as a positive alternative to the more radical wings of the civil rights movement, these initiatives asked residents to do what they had been doing for generations: building and maintaining their own communities.",
        "itemMedia":'<img class="content" src="images/09.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/09.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": " The Summerhill Riots",
        "itemSubhead": "Police Brutality and Racial Tension Lead to Violent Protests",
        "itemDescription": "In 1966, after multiple incidents of policy brutality in the all Black, working class neighborhood of Summerhill, and with tensions rising as planned urban renewal projects razed Black neighborhoods to build highways all around the city, a four-day protest erupted. Termed a riot by the media, the  four days of violence in Summerhill resulted in one death, multiple injuries and many arrests. Stokely Carmichael of the Student Nonviolent Coordinating Committee (SNCC) was accused of inciting the protests and the emerging militancy of the Black Power movement worried both white city leaders and more conservative Black leaders.",
        "itemMedia":'<img class="content" src="images/10.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/10.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "The Black Panthers in Atlanta",
        "itemSubhead": "The Black Panther Party Opens its Atlanta Office in Vine City",
        "itemDescription": "In early 1966 the Black Panther party opened an office in Vine City. According to Winston A. Grady-Willis in her book Atlanta and Black Struggles for Human Rights, the free breakfast program was a key component of the Atlanta office’s ability to recruit party members. Following the Summerhill incident, tensions in Vine City ran high. Similar to the national debates over the best tactics for gaining Black liberation, the Panthers, church ministers, SCLC and other more conservative activist groups in Vine City argued about the right approach to change. This photograph of riots in Vine City in 1967 illustrates the rising frustrations of many young, Black Atlantans.",
        "itemMedia":'<img class="content" src="images/11.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/11.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Suburbanization & a Shrinking Population",
        "itemSubhead": "By the mid-1970’s middle class families were starting to leave the Westside",
        "itemDescription": "By the 1970s, federal fair housing laws were enabling affluent Black families to move into formerly white city neighborhoods as well as some suburbs. Deteriorating conditions in Vine City and English avenue upset middle class residents and families began leaving the area. By the 1990's, residents began to notice that families were leaving in droves. Rebecca Jackson, interviewed in the clip here as a part of the Booker T. Washington high school 1988 oral history project, grew up in Vine City and recalls the changes to the neighborhood that began with families, including her own, moving out. In 1960 Vine City’s population was close to 9,000 but by 1980 that number had dropped to just over 6,000.",
        "itemMedia":'<div class="audioContainer"><audio controls><source src="images/audio1.mp3" type="audio/mpeg">Your browser does not support the audio element.</audio></div>',
        "itemThumb" : '<img class="content" src="thumbs/placeholder.jpg">',
        "mediaType" : "audio",
    },
    {
        "itemName": "The Development Train",
        "itemSubhead": "The Development Train",
        "itemDescription": "During the 1960’s and 70’s a burst of suburban malls were built as more and more whites and affluent Black Atlantans moved to the suburbs. At the same time Atlanta’s white business elite worked hard to shape the city; hotels and gleaming office towers cropped up all over the northern edge and in 1966 Atlanta became the first city to have two professional sports teams when the Milwaukee Braves moved to Atlanta. These business leaders envisioned a downtown constructed primarily for business conventions and worked with conservative state leaders to secure funding for the state-owned Georgia World Congress Center, which opened in 1976. Yet in 1973 the city also elected its first black mayor, Maynard Jackson. Many credit this delicate balance between Black and white business and political leaders with earlier city leaders’ pro-business approach to quieting racial unrest through compromise and back room deals. Whatever the behind the door tensions, the development train rarely slowed down during this time period. As the picture here illustrates, in the mid-1970’s the MARTA public transportation system was built, connecting the Westside communities more directly to downtown Atlanta, but not providing a comprehensive transit network that could have enabled access to the northern metro area where the most job growth was taking place.",
        "itemMedia":'<img class="content" src="images/12.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/12.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Westside Community Groups Fight Labor Building and Win",
        "itemSubhead": "Westside Residents gleeful after winning a development fight with the city",
        "itemDescription": "In 1986, in order to safeguard business interests and defuse racial tension, the Atlanta City Council voted to sell land in Vine City to the state to build a labor building. But community members did not want a labor building in their neighborhood and believed the vote and the sale of the land to be illegal; they filed a lawsuit in Fulton Superior Court and pushed for a re-vote. The Vine City Housing Ministry, a group of over 11 churches who used their collective power to put pressure on the city, emerged during this time period in order to both support and temper the activism of the community. In many ways the grassroots activism and resistance of this moment mirror the fervor of the mid-1960s. This photograph represents the community elation at having prevented this seizure of land. A protest flyer in the spirit of James Baldwin’s famous quote that “urban renewal is negro removal” reminds residents: “This is the worst case yet of urban removal in the disguise of urban renewal...Vine City is alive and we intend to fight…",
        "itemMedia":'<img class="content" src="images/13.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/13.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Resident speaking out against Dome at public meeting",
        "itemSubhead": "Eula Leake, 81, “Says Dome Might Upset Quiet Neighborhood”",
        "itemDescription": "At the same time community residents were fighting the labor building another group of powerful businessmen, investors and political leaders were already negotiating over the same piece of land residents were trying to save for housing. As early as 1985, plans for the first Georgia Dome were underway in Atlanta. The idea was not only to give the Atlanta Falcons a new stadium but to also set the city up to be a competitive site for the 1996 Olympics. This 1987 photograph and article from the Atlanta Journal Constitution provides a glimpse into the development focus of the time, while revealing the writer’s assumptions about the neighborhood’s origins. As the writer reports: “Because of its poverty, Vine City has been a thorn in the side of every city administration since at least the mid 1950’s. It is one of the city’s oldest black communities and, literally from the other side of the tracks, has supplied the doormen, maids, laborers, cashiers, cabbies, dishwashers and other laborers that have kept the city running for more than a century.”",
        "itemMedia":'<img class="content" src="images/14.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/14.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Church Leaders Band Together to Fight Dome",
        "itemSubhead": "As Plans for the Dome Move Forward, Church Leaders Organized",
        "itemDescription": "During early discussions and plans for the first Georgia Dome the possibility of moving Mount Vernon Baptist Church and Friendship Baptist church, two historic Black churches was brought up. This prompted the leaders of these churches to call on pastors and ministers from all over the Westside to help them challenge the development. All night vigils were held, the pastors threatened to stand in front of bulldozers and a widespread community response was mobilized. However, unlike the more grassroots approach to fighting the labor building, this group yielded its political power to ask for specific concessions and agreements, specifically provisions for high quality, affordable housing and a jobs training program. Meeting with Andrew Young and other city leaders behind closed doors, the ministers negotiated a deal so that the community could see real benefit from the project. In hindsight many such as Reverend Cottrell wonder whether this was a wise decision but at the time it felt like the only option.",
        "itemMedia":'https://player.vimeo.com/video/145558085?portrait=0',
        "itemThumb" : '<img class="content" src="thumbs/video05.jpg">',
        "mediaType" : "video",
    },
    {
        "itemName": "“They Trusted No One in the City”",
        "itemSubhead": "Reverend Cottrell explains the changing activist landscape",
        "itemDescription": "Reflecting back on the mid 1980’s, Reverend Cottrell outlines the reasons he thinks that community activists fought the labor building and the support role the church took during these struggles. When the debate over the development of the first Georgia Dome emerged soon after the labor building controversy, with the possibility of relocating historic Black churches, church leadership got in front of the struggle and led most of the action. With church leaders at the head of the struggle the negotiations became less about shutting down the development of the Dome—they saw that as inevitable—and more focused on negotiating agreements that would benefit the wider Vine City area.",
        "itemMedia":'https://player.vimeo.com/video/145562439?portrait=0',
        "itemThumb" : '<img class="content" src="thumbs/video04.jpg">',
        "mediaType" : "video",
    },
    {
        "itemName": "The City Council Votes",
        "itemSubhead": "In August, 1988 the city voted to approve the Dome but they listed a number of stipulations.",
        "itemDescription": "As the Atlanta Daily World reported: the council voice “bellowed loud and clear: “you can build the Dome providing you do your part in taking care of the residents of Vine City.” The city council’s 1998 stipulations included:<ul><li>A surcharge of 25 cents to $1 on tickets to stadium events to augment the ten million dollar trust fund</li><li>Any money left over after the stadium’s expected operating deficit would go back to the city</li><li>The city would not have to pay for infrastructure around the Dome</li><li>The Stadium Corporation would be required to ensure that 35% of the people working on the construction of the Dome were minorities</li><li>20% of supplies bought for operations after the stadium opens must be purchased from minority firms</li><li>The Stadium Corp. would be required to pick up any legal expenses caused by lawsuits stemming from the city’s involvement</li></ul>",
        "itemMedia":'<img class="content" src="images/15.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/15.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Compromise after Political Pressure",
        "itemSubhead": "Nearly a year later Final Approval for the Dome Scraps Stipulations",
        "itemDescription": "On June 8, 1989, and June 9, 1989, after the state had approved the Dome – with none of the city’s original stipulations remaining in the deal, the city council and Fulton County voted unanimously in favor of building the Dome. This was the result of compromise and pressure from the state and was representative of the back room political maneuverings typical of Atlanta development politics. As the Atlanta Daily World reports: “Disagreements over the project last week led to reports the stadium would not be built, but civic leaders spent the weekend settling disputes.” After the Fulton County vote, then chairmen of the commission and mayor hopeful Michael Lomax exclaimed, “The Dome is done. Long live the Dome!”",
        "itemMedia":'<img class="content" src="images/16.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/16.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Vine City Residents Not Pleased About Dome",
        "itemSubhead": "At the Community Level Many Residents Felt Betrayed by the Process",
        "itemDescription": "Despite the leverage of various Black city council members and church leaders, many Vine City residents, especially the residents of Lightning, were not pleased about the Dome. Haniyfa A. Ali, a community activist from Lightning, told reporters: “We don’t need to sell out Vine City for ten million dollars.” And in this May 1988 interview from the Booker T. Washington oral history project, Clarence Williams, International Representative with the United Auto Workers Union who grew up in t Herndon Homes, expresses his frustration with the process.",
        "itemMedia":'<img class="content" src="images/17.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/17.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Ivory Young Discusses the “Taking” of Lightning",
        "itemSubhead": "Looking Back on What Happened to Lightning",
        "itemDescription": "In 2015 Councilmen Young was interviewed about his memory of the negotiations over the 1992 Georgia Dome. Councilman Young worked for the architectural and construction firm that designed and managed the construction of the 150 homes that were to be built using the ten million dollar trust fund. He looks back on the way that the 1992 Dome negotiation took place, reflecting with dismay over the injustice of what happened to the community of Lightning.",
        "itemMedia":'https://player.vimeo.com/video/145779833?portrait=0',
        "itemThumb" : '<img class="content" src="thumbs/18.jpg">',
        "mediaType" : "video",
    },
    {
        "itemName": "Work Begins on Affordable Housing in Vine City",
        "itemSubhead": "By 1990 Work Had Begun on Affordable Housing Units Tied to Stadium Agreement",
        "itemDescription": "In May of 1990, groundbreaking for the 150 planned single-family houses in Vine City began. Ultimately, most of the funding for the trust fund came from the city and the county, with two million dollars promised from private funds to be raised by the Stadium Corporation. While the homes were relatively affordable, homeowners had to qualify for the $55,000 mortgage and have an income of about $17,000 a year. Plans were to complete construction of the houses over the next 3 years and as this picture shows construction began immediately. ",
        "itemMedia":'<img class="content" src="images/19.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/19.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Selling 150 Affordable Housing Units Proves Difficult",
        "itemSubhead": "Housing Ministry Finding Few Who Qualify for Low-Price Homes",
        "itemDescription": "Optimism about the 150 affordable units started to wane by October 1990 when the 11 churches working together under the Vine City Housing Ministry reported that they had only been able to sell 1 of the 5 houses constructed. Much of this had to do with the relative poverty of neighborhood residents and the fact that even “affordable” housing was out of reach for them. As the Atlanta Journal Constitution reported: “Of the 400 applications distributed, 300 were returned but only 1 qualified.” The problems were also tied to market logic. Trying to sell new houses that cost $40,000 - $60,000 right next to vacant lots or old homes that had been sitting empty for decades proved a challenge, as this photograph shows.",
        "itemMedia":'<img class="content" src="images/20.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/20.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Disputing the Blame Placed on the Vine City Housing Ministry",
        "itemSubhead": "In a 2015 Interview Cottrell Disputes Claims that Housing Ministry was at Fault",
        "itemDescription": "The October 1990 problems with building housing were only a small indication of the troubles to come. The Vine City Housing Ministry not only faced challenges selling and financing the houses, but since they did not have expertise in the building trades, they also had trouble managing their role as community developers. Meanwhile, city, state and county officials and the various investors in the project also played roles: advising the ministry, selecting developers and checking in on their progress. The historical record shows a complex web of decision-making. Moreover, structural factors, such as racist lending policies, metropolitan expansion and the departure of more fortunate residents from Vine City, made selling land in the area difficult. However, the contemporary story about what happened places most of the blame on the churches and community developers. In this recent interview, Reverend Cottrell goes back to his memories of the 1990’s and challenges the media interpretation that failure was entirely the fault of the ministry.",
        "itemMedia":'https://player.vimeo.com/video/145780308?portrait=0',
        "itemThumb" : '<img class="content" src="thumbs/video04.jpg">',
        "mediaType" : "video",
    },
    {
        "itemName": "Demolition of Public Housing in Atlanta",
        "itemSubhead": "Starting in 1994 the Atlanta Housing Authority began demolishing public housing projects",
        "itemDescription": "Based on the perception that public housing was a failure, and fueled by funds from the U.S. Department of Housing and Urban Development's Hope VI, the Atlanta Housing Authority adopted a plan to replace low-income public housing projects with mixed income communities.  The Housing Authority received the first pilot grant in 1993.  Begun in 1994, the demolition continued through 2011.  While there have been some successes with the model of mixed income communities, Deirdre Oakley, assistant professor at Georgia State, has done a study that suggests that many residents have been relocated to neighborhoods that are not significantly better than those they left and most of the housing is from the private rental market which does not guarantee availability to low income residents.",
        "itemMedia":'<img class="content" src="images/23.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/23.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "1996 Olympics",
        "itemSubhead": "In spite of promises, the Olympic Games in 1996 did not bring improvements to the Westside",
        "itemDescription": "Eminent domain was used by the city to demolish homes in order to accommodate the expansion of the Dome area to provide venues and parking for the 1996 Olympics.  Although the city made much of public/private partnerships to improve the neighborhoods around Olympic Park, residents felt, once again, let down by the gap between the promises made and the outcome of events.",
        "itemMedia":'<img class="content" src="images/placeholder.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/placeholder.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Under Water: A Flood, Tornado and the 2007 Foreclosure Crisis",
        "itemSubhead": "1997-2008: Hardship on the Westside",
        "itemDescription": "After the excitement of the 1996 Olympics receded, residents of the Westside noticed little economic benefit from the influx of money that came in during the surge of development. Instead, by 2001 another jobs recession was hurting an area already plagued by unemployment and poverty and the housing boom was spurring investment but little change. When the 2007 Great Recession hit and the housing bubble burst, more buildings and houses were left empty, homeowners were underwater on mortgages (many of them given under fraudulent conditions) and renters were being evicted from homes owned by absentee landlords. A 2002 flood and an outdated sewer system put parts of the Westside 6 feet under water and a 2008 tornado again ravaged the neighborhood.",
        "itemMedia":'<img class="content" src="images/placeholder.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/placeholder.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Controversy over the New Georgia Dome",
        "itemSubhead": "In 2010 The Falcons Announce plans for a new Dome & Controversy Emerges",
        "itemDescription": "In the summer of 2010 Falcons owner Arthur Blank and his executive team began private meetings with elected officials to make known their desire for a new, open-air stadium.  Elected officials were torn. The legacy of the benefits to the city, and especially to the neighborhoods right around the dome, were not great and a massive amount of public dollars would have to help finance the dome. By 2012, after the pricetag had gone up considerably and a public survey revealed that 75% of Atlantans were against the Dome, Georgia Senator Vincent Fort wrote an opinion piece in the Atlanta Journal Constitution saying that he regretted voting to help finance the dome: “Is public funding of sports teams -- bonding support or other direct taxes -- a legitimate municipal or state government undertaking?...I say let the Falcons and the NFL finance their own facility. It would be better to use hundreds of millions of taxpayer dollars to improve education as an economic driver than to support a sports team owner.”",
        "itemMedia":'<img class="content" src="images/25.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/25.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "A New Round of Promises",
        "itemSubhead": "Along with the Controversy came Negotiations over Community Benefits",
        "itemDescription": "Learning their lesson from the public outcry during the negotiations over the 1992 Dome, policymakers and the Arthur Blank Foundation worked to prevent major disruptions to their process by setting up a community benefits committee, selecting specific neighborhood leaders from Vine City, English Avenue and Castleberry Hill to participate, and outlining the scope of the projects that would be funded through the process. Yet despite promises to give $30 million to support workforce development, public safety, education and more, community residents questioned whether this was enough and were skeptical about whether there would be a return on the public’s investment. In this video clip Hattie Dorsey, Founder and former president of the Atlanta Neighborhood Development Partnership (ANDP), questions the community benefits process and the usefulness of the funds promised to the Westside. ",
        "itemMedia":'<img class="content" src="images/placeholder.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/placeholder.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Residents Skeptical about new Georgia Dome’s Promises",
        "itemSubhead": "Residents not Included in the Debate also have a Stake",
        "itemDescription": "Along with policymakers and leaders, the residents of the Westside, who have lived and worked to make these neighborhoods better over the years have a stake in helping to shape the future. In a 2013 long-form piece on the new stadium in the Atlanta Magazine called “It’s going to take more than $45 million* to help Vine City,” Greg Hawthorne, current executive director of the Vine City Health and Housing Ministry” told reporters that the community benefits “really needs to translate into what the community needs. Jobs. Not just minimum wage jobs, but living wage jobs.” <br>Residents themselves, and not just the ones usually representing community at meetings or being interviewed by the media have ideas about what needs to happen and vested interests in seeing change occur. In this 2015 interview, Sandra Walker, who has lived in the Westside since birth talks about why she remains living there. Echoing the worries of many residents, she says that she is concerned that not only will the new Dome not help the neighborhood but that the plans are to push current residents out. ",
        "itemMedia":'https://player.vimeo.com/video/145885412?portrait=0',
        "itemThumb" : '<img class="content" src="thumbs/26.jpg">',
        "mediaType" : "video",
    },
    {
        "itemName": "Name Here",
        "itemSubhead": "Subheadline here",
        "itemDescription": "Description can be much longer, but should be limited to 260 characters... Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
        "itemMedia":'<img class="content" src="images/placeholder.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/placeholder.jpg">',
        "mediaType" : "image",
    },

]