//theme racism
var stories0 = [
    {
    	"itemName": "1906 Race Riot",
    	"itemSubhead": "Racial Violence Prompts Migration",
    	"itemDescription": "Uncomfortable with the city’s growing Black population and increased visibility, white Atlantans launched an orgy of violence after the city's main newspapers printed false rumors of Black men raping white women. Rioters targeted prosperous Black-owned downtown businesses like barbershops, as well as establishments along the Decatur Avenue entertainment strip, some of which served an interracial clientele.  At least 25 Blacks (and 2 whites) were killed in the violence which lasted for nearly three days.  Although at least one Eastside Black neighborhood organized a successful armed defense of their community,  the increasingly hostile atmosphere convinced many Black Atlantans to regroup on the Westside.",
    	"itemMedia":'<img class="content" src="images/01.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/01.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "The Impact of Redlining & Atlanta’s Racial Segregation Laws",
        "itemSubhead": "Government-Backed Racist Housing Policy",
        "itemDescription": "In the 1930s, the federal government commissioned and circulated a series of maps rating city neighborhoods by supposed mortgage lending risk. These maps specified four “grades,” with all African American residential areas, regardless of income, rated as the lowest, “D” (or “red”) neighborhoods – hence the term “redlining.”, Assessors classified Atlanta’s entire Westside as a high-risk area – setting in motion a self-fulfilling prophecy as banks subsequently refused to lend in the area. Moreover, local whites pursued similar efforts on the municipal level, passing racial segregation ordinances in 1913, 1916, 1929, and 1931 - despite Supreme Court rulings in 1917 and 1924 that such laws were unconstitutional.  Even though these particular attempts failed, it demonstrates how determined whites were to keep African Americans out of “their” neighborhoods.",
        "itemMedia":'<img class="content" src="images/04.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/04.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Public Housing Developments Displace Residents",
        "itemSubhead": "Supposed “Slums” Demolished to Make Way for New Developments",
        "itemDescription": "Thousands of Black residents were displaced when the Atlanta Housing Authority started building public housing in the mid-1930s. As in virtually all American cities at the time, these housing projects were racially segregated, formally in the South but informally in the North prior to 1964.  Not all of the housing destroyed fit the description of “slums” that was used to justify these projects. This man, moving his family’s belongings prior to the opening of the Alonzo Herndon Homes in 1941, may have hauled ice for a living, small-scale entrepreneurship being a strategy some Black men successfully used to avoid racial discrimination in the workplace.  Black homeowners in the demolished areas typically did not receive fair market value for their homes, and faced the predicament of finding new housing in a segregated market with many areas off-limits to them.",
        "itemMedia":'<img class="content" src="images/05.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/05.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Changing Demographics",
        "itemSubhead": "Affordable Housing on the Westside: 1940's - 1960's",
        "itemDescription": "By 1930 Vine City and most of the Westside was majority-Black. Exceptions did exist – working class white families continued to live in the area through the 1940’s, especially in “Bellwood” (present day English Avenue) – but as increasing numbers of Black families moved to the area in the 1940's and 1950's, when all Black housing projects were built, white families continued to move out.",
        "itemMedia":'<img class="content" src="images/06.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/06.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Martin Luther King Jr. Leads Demonstrations for Fair Housing in Vine City",
        "itemSubhead": "1960's Rising Tensions over Racial Discrimination Result in Protests",
        "itemDescription": "In the 1960’s issues over racial discrimination across housing, services and infrastructure erupted in protests. Common issues facing Black families included: overpaying for sub-standard housing; absentee landlords ignoring tenants’ requests; lack of access to affordable and high quality food; and laws, policies and social practices that forced Black families into the least desirable, low-lying parts of the city where poor drainage and sanitation problems were prevalent. Moreover, in Atlanta, the city refused to pave streets in Black neighborhoods into the 1950s and in the early twentieth century, even refused to pick up garbage. In 1966 Martin Luther King Jr. and Coretta Scott, who, in 1965 had moved into a home at 239 Sunset Avenue in Vine City, led a protest in the neighborhood against the unsafe and unfair housing conditions.",
        "itemMedia":'<img class="content" src="images/07.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/07.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "1960 English Avenue School Bombing",
        "itemSubhead": "Bombing Leads the Nation to Question Whether Atlanta is the “City too Busy to Hate.”",
        "itemDescription": "This 1960 Chicago Tribune Coverage of the English Avenue School Bombing describes a horrific scene:<br><br>“Atlanta, Dec. 12 - A dynamite bomb blasted a Negro elementary school early today...The blast occurred hours before school opened and no one was injured. Sixteen hundred children attend the school. Police theorized that the bomb, composed of 10 sticks of dynamite, was thrown against the school from a passing car…”<br><br>The school is in a middle class Negro neighborhood and within two block of white dwellings and 10 blocks from the Georgia Tech campus. There was speculation that the bombing was the work of groups fighting against mixing of the races in Atlanta's schools.”",
        "itemMedia":'<img class="content" src="images/08.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/08.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Schisms Between Civil Rights Movement Groups Rise in the Mid-Late 60’s",
        "itemSubhead": "Multiple Community Development, Civil Rights and Black Power activist groups in Vine City in the 1960’s and 70’s.",
        "itemDescription": "In the mid-1960’s not only were leaders from the Southern Christian Leadership Council (SCLC) and the Student Nonviolent Coordinating Committee (SNCC) active in the community, but area colleges and universities and early public-private initiatives such as the Council on Human Relations of Greater Atlanta, Inc. spearheaded projects as well. An example of such a project is the “Vine City Project: Experiments in Self Help” which paired area college students with community members to work on cleanup projects and other “experiments” in community self directed development. Seen by many as a positive alternative to the more radical wings of the civil rights movement, these initiatives asked residents to do what they had been doing for generations: building and maintaining their own communities.",
        "itemMedia":'<img class="content" src="images/09.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/09.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "The Summerhill Riots",
        "itemSubhead": "Police Brutality and Racial Tension Lead to Violent Protests",
        "itemDescription": "In 1966, after multiple incidents of policy brutality in the all Black, working class neighborhood of Summerhill, and with tensions rising as planned urban renewal projects razed Black neighborhoods to build highways all around the city, a four-day protest erupted. Termed a riot by the media, the  four days of violence in Summerhill resulted in one death, multiple injuries and many arrests. Stokely Carmichael of the Student Nonviolent Coordinating Committee (SNCC) was accused of inciting the protests and the emerging militancy of the Black Power movement worried both white city leaders and more conservative Black leaders.",
        "itemMedia":'<img class="content" src="images/10.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/10.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "The Black Panthers in Atlanta",
        "itemSubhead": "The Black Panther Party Opens its Atlanta Office in Vine City",
        "itemDescription": "In early 1966 the Black Panther party opened an office in Vine City. According to Winston A. Grady-Willis in her book Atlanta and Black Struggles for Human Rights, the free breakfast program was a key component of the Atlanta office’s ability to recruit party members. Following the Summerhill incident, tensions in Vine City ran high. Similar to the national debates over the best tactics for gaining Black liberation, the Panthers, church ministers, SCLC and other more conservative activist groups in Vine City argued about the right approach to change. This photograph of riots in Vine City in 1967 illustrates the rising frustrations of many young, Black Atlantans.",
        "itemMedia":'<img class="content" src="images/11.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/11.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Vine City Residents Not Pleased About Dome",
        "itemSubhead": "At the Community Level Many Residents Felt Betrayed by the Process",
        "itemDescription": "Despite the leverage of various Black city council members and church leaders, many Vine City residents, especially the residents of Lightning, were not pleased about the Dome. Haniyfa A. Ali, a community activist from Lightning, told reporters: “We don’t need to sell out Vine City for ten million dollars.” And in this May 1988 interview from the Booker T. Washington oral history project, Clarence Williams, International Representative with the United Auto Workers Union who grew up in t Herndon Homes, expresses his frustration with the process.",
        "itemMedia":'<img class="content" src="images/17.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/17.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "The Color of Money",
        "itemSubhead": "The Atlanta Journal Constitution’s Exposes Widespread Racist Lending Practices in 1989 Series",
        "itemDescription": "Another challenge faced by the Vine City Housing Ministry that the media did not discuss was the practice of racist lending policies, prevalent from the late 1980’s and into the early 1990’s. In 1989 the Atlanta Journal Constitution ran a Pulitzer Prize winning series called The Color of Money, which investigated the impact of race on lending practices in the city of Atlanta. The report uncovered sad truths about lending practices and put into context the severe economic and social challenges facing Black families in the city. As the maps here show, the Westside communities were at the heart of this structural problem.",
        "itemMedia":'<img class="content" src="images/22.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/22.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Demolition of Public Housing in Atlanta",
        "itemSubhead": "Starting in 1994 the Atlanta Housing Authority began demolishing public housing projects",
        "itemDescription": "Based on the perception that public housing was a failure, and fueled by funds from the U.S. Department of Housing and Urban Development's Hope VI, the Atlanta Housing Authority adopted a plan to replace low-income public housing projects with mixed income communities.  The Housing Authority received the first pilot grant in 1993.  Begun in 1994, the demolition continued through 2011.  While there have been some successes with the model of mixed income communities, Deirdre Oakley, assistant professor at Georgia State, has done a study that suggests that many residents have been relocated to neighborhoods that are not significantly better than those they left and most of the housing is from the private rental market which does not guarantee availability to low income residents.",
        "itemMedia":'<img class="content" src="images/23.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/23.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Under Water: A Flood, Tornado and the 2007 Foreclosure Crisis",
        "itemSubhead": "1997-2008: Hardship on the Westside",
        "itemDescription": "After the excitement of the 1996 Olympics receded, residents of the Westside noticed little economic benefit from the influx of money that came in during the surge of development. Instead, by 2001 another jobs recession was hurting an area already plagued by unemployment and poverty and the housing boom was spurring investment but little change. When the 2007 Great Recession hit and the housing bubble burst, more buildings and houses were left empty, homeowners were underwater on mortgages (many of them given under fraudulent conditions) and renters were being evicted from homes owned by absentee landlords. A 2002 flood and an outdated sewer system put parts of the Westside 6 feet under water and a 2008 tornado again ravaged the neighborhood.",
        "itemMedia":'<img class="content" src="images/placeholder.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/placeholder.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Two line name, 30 characters",
        "itemSubhead": "Two line subhead, 37 characters limit",
        "itemDescription": "Description can be much longer, but should be limited to 260 characters... Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
        "itemMedia":'<img class="content" src="images/placeholder.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/placerholder.jpg">',
        "mediaType" : "image",
    },

]