//this is currently the json file with all the content
var stories = [
    {
    	"itemName": "Fire in Old Fourth Ward",
    	"itemSubhead": "1917 Great Atlanta Fire",
    	"itemDescription": "In 1917 The Great Atlanta Fire destroyed many homes on Auburn Avenue and in the 4th Ward, where most Black families lived up until then. This caused mass migration of Black families to other areas of Atlanta. Many Black families moved to present day English Avenue and Vine City.",
    	"itemMedia":'<img class="content" src="images/omeka1.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/omeka1.jpg">',
        "mediaType" : "image",
    },
    {
    	"itemName": "Myrtle Dansby",
    	"itemSubhead": "English Avenue in the 1950's",
    	"itemDescription": "Myrtle Dansby moved from Old Fourth Ward to English Avenue in 1949 and has lived in the area for the last sixty-six years. She has fond memories of living in the neighborhood in the 1950's and 1960's.",
    	"itemMedia":'https://player.vimeo.com/video/134208479?title=0&byline=0&portrait=0?api=1',
        "itemThumb" : '<img class="content" src="thumbs/video01.jpg">',
        "mediaType" : "video",
    },
    {
    	"itemName": "Changing Demographics",
    	"itemSubhead": "Affordable Housing on the Westside: 1940's - 1960's",
    	"itemDescription": "Both White and Black families lived in the Westside through the 1940's. But as increasing numbers of Black families moved to the area in the 1940's and 1950's (when all Black housing projects were built) White families began to move out.",
    	"itemMedia":'<img class="content" src="images/omeka2.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/omeka2.jpg">',
        "mediaType" : "image",
    },
    {
    	"itemName": "1960's Protests for Fair Housing",
    	"itemSubhead": "1960's rising tension results in protests",
    	"itemDescription": "Racial discrimination, sub-standard housing and various other issues were at the center of struggles across Atlanta, the south and the nation. In 1966 Martin Luther King Jr. and Coretta Scott led a protest in Vine Cityagainst the unsafe and unfair housing conditions.",
    	"itemMedia":'<img class="content" src="images/omeka3.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/omeka3.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Tillman Ward ",
        "itemSubhead": "Changes to the Westside Landscape",
        "itemDescription": "Tilman Ward was born in the 1940's in Vine City. Tilman's memories of his early life, combined with his knowledge of history, help to illustrate the scale at which the physical and social spaces of the neighborhood have changed over the last half a century.",
        "itemMedia":'https://www.youtube.com/embed/vmKH0F9RyBY',
        "itemThumb" : '<img class="content" src="thumbs/video02.jpg">',
        "mediaType" : "video",
    },
    {
        "itemName": "Tre Lockhardt",
        "itemSubhead": "Suburbanization",
        "itemDescription": "In the 1970's, changing segregation laws in the suburbs allowed affluent Black families to move into these neighborhoods. Deteriorating conditions in Vine City and English avenue upset middle class residents and families began leaving the area. By the 1990's, residents like Tre Lockhart (see video clip) began to notice that families were leaving in droves.",
        "itemMedia":'https://www.youtube.com/embed/aTBJd6hFTas',
        "itemThumb" : '<img class="content" src="thumbs/video03.jpg">',
        "mediaType" : "video",
    },
    {
        "itemName": "Flyer Protests First Dome",
        "itemSubhead": "Church Leaders Organize in Response",
        "itemDescription": "As early as 1985 plans for the first Georgia Dome were underway in Atlanta. This Southern Christian Leadership Conference (SCLC) flyer shows the community's concerns about the Dome and the lack of community imput in the process. ",
        "itemMedia":'<img class="content" src="images/omeka4.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/omeka4.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Vine City to Fight Dome",
        "itemSubhead": '"Monster Moving in our Direction"',
        "itemDescription": "By 1987 ministers and community members stood together against the Dome and against what they saw as an unjust city, state and county approach to building with little community input in their backyards. Both Reverend Cottrell and Tilman Ward speak out about the injustice of the process. ",
        "itemMedia":'<img class="content" src="images/omeka5.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/omeka5.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "1988 County Commissioner Nancy Boxill",
        "itemSubhead": "1992 Georgia Dome and Relocation ",
        "itemDescription": "By 1988 residents of Vine City, Lightning and other surrounding communities had been told the Dome was coming but had little input into the process. Nancy Boxill, then County Commissioner, answers Booker T. Washington students' questions.",
        "itemMedia":'<div class="audioContainer"><audio controls><source src="images/audio.mp3" type="audio/mpeg">Your browser does not support the audio element.</audio></div>',
        "itemThumb" : '<img class="content" src="thumbs/placeholder.jpg">',
        "mediaType" : "audio",
    },
    {
        "itemName": "Down on the Dome",
        "itemSubhead": "Vine City Housing Ministry and the $10 million Trust Fund",
        "itemDescription": "After tense negotiations, Vine City won the 10 million dollar trust fund in 1990 but as of 1992--when the Dome opened to the public--only 42 houses had been built and the business community had not raised its 2 million dollar share of the fund.",
        "itemMedia":'<img class="content" src="images/omeka6.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/omeka6.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Reverend W.L. Cottrell",
        "itemSubhead": "The Vine City Housing Ministry and the 1992 Dome",
        "itemDescription": "Reverend W.L Cottrell, Pastor Emeritus at the Beulah Baptist Church in Vine City and Former Director of the Vine City Housing Ministry, discusses the lead up to the decision to build the 1992 stadium near Vine City and English Avenue.",
        "itemMedia":'https://player.vimeo.com/video/125599211?title=0&byline=0&portrait=0',
        "itemThumb" : '<img class="content" src="thumbs/video04.jpg">',
        "mediaType" : "video",
    },
    {
        "itemName": "Hattie Dorsey",
        "itemSubhead": "Details of Vine City's Deal With the City",
        "itemDescription": "Hattie Dorsey thinks that the city council responded well to community concerns during the first Dome poject (city council passed the legislation to establish the ten million dollar trust fund for housing). However, she thinks the problem was with the city's admin of the project. ",
        "itemMedia":'https://player.vimeo.com/video/126172733?title=0&byline=0&portrait=0',
        "itemThumb" : '<img class="content" src="thumbs/video05.jpg">',
        "mediaType" : "video",
    },
    {
        "itemName": "The Color of Money",
        "itemSubhead": "1989 Articles Exposes Racist Lending",
        "itemDescription": "In 1989 the Atlanta Journal Constitution ran a Pullitzer Prize winning series called The Color of Money, which investigated how race impacted lending practices in the city of Atlanta. The investigative reporting uncovered sad truths about lending practices in the 1980's.",
        "itemMedia":'<img class="content" src="images/omeka7.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/omeka7.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Two line name, 30 characters",
        "itemSubhead": "Two line subhead, 37 characters limit",
        "itemDescription": "Description can be much longer, but should be limited to 260 characters... Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
        "itemMedia":'<img class="content" src="images/placeholder.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/placerholder.jpg">',
        "mediaType" : "image",
    },

]