//theme activism
var stories3 = [
    {
        "itemName": "Schisms Between Civil Rights Movement Groups Rise in the Mid-Late 60’s",
        "itemSubhead": "Multiple Community Development, Civil Rights and Black Power activist groups in Vine City in the 1960’s and 70’s.",
        "itemDescription": "In the mid-1960’s not only were leaders from the Southern Christian Leadership Council (SCLC) and the Student Nonviolent Coordinating Committee (SNCC) active in the community, but area colleges and universities and early public-private initiatives such as the Council on Human Relations of Greater Atlanta, Inc. spearheaded projects as well. An example of such a project is the “Vine City Project: Experiments in Self Help” which paired area college students with community members to work on cleanup projects and other “experiments” in community self directed development. Seen by many as a positive alternative to the more radical wings of the civil rights movement, these initiatives asked residents to do what they had been doing for generations: building and maintaining their own communities.",
        "itemMedia":'<img class="content" src="images/09.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/09.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "The Black Panthers in Atlanta",
        "itemSubhead": "The Black Panther Party Opens its Atlanta Office in Vine City",
        "itemDescription": "In early 1966 the Black Panther party opened an office in Vine City. According to Winston A. Grady-Willis in her book Atlanta and Black Struggles for Human Rights, the free breakfast program was a key component of the Atlanta office’s ability to recruit party members. Following the Summerhill incident, tensions in Vine City ran high. Similar to the national debates over the best tactics for gaining Black liberation, the Panthers, church ministers, SCLC and other more conservative activist groups in Vine City argued about the right approach to change. This photograph of riots in Vine City in 1967 illustrates the rising frustrations of many young, Black Atlantans.",
        "itemMedia":'<img class="content" src="images/11.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/11.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Westside Community Groups Fight Labor Building and Win",
        "itemSubhead": "Westside Residents gleeful after winning a development fight with the city",
        "itemDescription": "In 1986, in order to safeguard business interests and defuse racial tension, the Atlanta City Council voted to sell land in Vine City to the state to build a labor building. But community members did not want a labor building in their neighborhood and believed the vote and the sale of the land to be illegal; they filed a lawsuit in Fulton Superior Court and pushed for a re-vote. The Vine City Housing Ministry, a group of over 11 churches who used their collective power to put pressure on the city, emerged during this time period in order to both support and temper the activism of the community. In many ways the grassroots activism and resistance of this moment mirror the fervor of the mid-1960s. This photograph represents the community elation at having prevented this seizure of land. A protest flyer in the spirit of James Baldwin’s famous quote that “urban renewal is negro removal” reminds residents: “This is the worst case yet of urban removal in the disguise of urban renewal...Vine City is alive and we intend to fight…",
        "itemMedia":'<img class="content" src="images/13.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/13.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Church Leaders Band Together to Fight Dome",
        "itemSubhead": "As Plans for the Dome Move Forward, Church Leaders Organized",
        "itemDescription": "During early discussions and plans for the first Georgia Dome the possibility of moving Mount Vernon Baptist Church and Friendship Baptist church, two historic Black churches was brought up. This prompted the leaders of these churches to call on pastors and ministers from all over the Westside to help them challenge the development. All night vigils were held, the pastors threatened to stand in front of bulldozers and a widespread community response was mobilized. However, unlike the more grassroots approach to fighting the labor building, this group yielded its political power to ask for specific concessions and agreements, specifically provisions for high quality, affordable housing and a jobs training program. Meeting with Andrew Young and other city leaders behind closed doors, the ministers negotiated a deal so that the community could see real benefit from the project. In hindsight many such as Reverend Cottrell wonder whether this was a wise decision but at the time it felt like the only option.",
        "itemMedia":'https://player.vimeo.com/video/145558085?portrait=0',
        "itemThumb" : '<img class="content" src="thumbs/video05.jpg">',
        "mediaType" : "video",
    },
    {
        "itemName": "“They Trusted No One in the City”",
        "itemSubhead": "Reverend Cottrell explains the changing activist landscape",
        "itemDescription": "Reflecting back on the mid 1980’s, Reverend Cottrell outlines the reasons he thinks that community activists fought the labor building and the support role the church took during these struggles. When the debate over the development of the first Georgia Dome emerged soon after the labor building controversy, with the possibility of relocating historic Black churches, church leadership got in front of the struggle and led most of the action. With church leaders at the head of the struggle the negotiations became less about shutting down the development of the Dome—they saw that as inevitable—and more focused on negotiating agreements that would benefit the wider Vine City area.",
        "itemMedia":'https://player.vimeo.com/video/145562439?portrait=0',
        "itemThumb" : '<img class="content" src="thumbs/video04.jpg">',
        "mediaType" : "video",
    },
    {
        "itemName": "The City Council Votes",
        "itemSubhead": "In August, 1988 the city voted to approve the Dome but they listed a number of stipulations.",
        "itemDescription": "As the Atlanta Daily World reported: the council voice “bellowed loud and clear: “you can build the Dome providing you do your part in taking care of the residents of Vine City.” The city council’s 1998 stipulations included:<ul><li>A surcharge of 25 cents to $1 on tickets to stadium events to augment the ten million dollar trust fund</li><li>Any money left over after the stadium’s expected operating deficit would go back to the city</li><li>The city would not have to pay for infrastructure around the Dome</li><li>The Stadium Corporation would be required to ensure that 35% of the people working on the construction of the Dome were minorities</li><li>20% of supplies bought for operations after the stadium opens must be purchased from minority firms</li><li>The Stadium Corp. would be required to pick up any legal expenses caused by lawsuits stemming from the city’s involvement</li></ul>",
        "itemMedia":'<img class="content" src="images/15.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/15.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Vine City Residents Not Pleased About Dome",
        "itemSubhead": "At the Community Level Many Residents Felt Betrayed by the Process",
        "itemDescription": "Despite the leverage of various Black city council members and church leaders, many Vine City residents, especially the residents of Lightning, were not pleased about the Dome. Haniyfa A. Ali, a community activist from Lightning, told reporters: “We don’t need to sell out Vine City for ten million dollars.” And in this May 1988 interview from the Booker T. Washington oral history project, Clarence Williams, International Representative with the United Auto Workers Union who grew up in t Herndon Homes, expresses his frustration with the process.",
        "itemMedia":'<img class="content" src="images/17.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/17.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Under Water: A Flood, Tornado and the 2007 Foreclosure Crisis",
        "itemSubhead": "1997-2008: Hardship on the Westside",
        "itemDescription": "After the excitement of the 1996 Olympics receded, residents of the Westside noticed little economic benefit from the influx of money that came in during the surge of development. Instead, by 2001 another jobs recession was hurting an area already plagued by unemployment and poverty and the housing boom was spurring investment but little change. When the 2007 Great Recession hit and the housing bubble burst, more buildings and houses were left empty, homeowners were underwater on mortgages (many of them given under fraudulent conditions) and renters were being evicted from homes owned by absentee landlords. A 2002 flood and an outdated sewer system put parts of the Westside 6 feet under water and a 2008 tornado again ravaged the neighborhood.",
        "itemMedia":'<img class="content" src="images/placeholder.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/placeholder.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Controversy over the New Georgia Dome",
        "itemSubhead": "In 2010 The Falcons Announce plans for a new Dome & Controversy Emerges",
        "itemDescription": "In the summer of 2010 Falcons owner Arthur Blank and his executive team began private meetings with elected officials to make known their desire for a new, open-air stadium.  Elected officials were torn. The legacy of the benefits to the city, and especially to the neighborhoods right around the dome, were not great and a massive amount of public dollars would have to help finance the dome. By 2012, after the pricetag had gone up considerably and a public survey revealed that 75% of Atlantans were against the Dome, Georgia Senator Vincent Fort wrote an opinion piece in the Atlanta Journal Constitution saying that he regretted voting to help finance the dome: “Is public funding of sports teams -- bonding support or other direct taxes -- a legitimate municipal or state government undertaking?...I say let the Falcons and the NFL finance their own facility. It would be better to use hundreds of millions of taxpayer dollars to improve education as an economic driver than to support a sports team owner.”",
        "itemMedia":'<img class="content" src="images/25.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/25.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Name Here",
        "itemSubhead": "Subheadline here",
        "itemDescription": "Description can be much longer, but should be limited to 260 characters... Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
        "itemMedia":'<img class="content" src="images/placeholder.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/placeholder.jpg">',
        "mediaType" : "image",
    },

]