//theme housing
var stories1 = [
    {
    	"itemName": "Alonzo Herndon Family Home",
    	"itemSubhead": "Economic Diversity in the Early 20th Century",
    	"itemDescription": "The former home of Atlanta’s first Black millionaire, Alonzo Herndon, sits on the southern border of Vine City. Herndon arrived in 1883 and started a prosperous barbering business; he also invested in real estate and in 1905 founded the Atlanta Life Insurance Company, a crucial lifeline at a time when many white-owned companies refused policies to Blacks. Built in 1910, the Herndon family home harks back to an earlier era when the Westside housed residents from a mixture of economic backgrounds.",
    	"itemMedia":'<img class="content" src="images/02.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/02.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "The Impact of Redlining & Atlanta’s Racial Segregation Laws",
        "itemSubhead": "Government-Backed Racist Housing Policy",
        "itemDescription": "In the 1930s, the federal government commissioned and circulated a series of maps rating city neighborhoods by supposed mortgage lending risk. These maps specified four “grades,” with all African American residential areas, regardless of income, rated as the lowest, “D” (or “red”) neighborhoods – hence the term “redlining.”, Assessors classified Atlanta’s entire Westside as a high-risk area – setting in motion a self-fulfilling prophecy as banks subsequently refused to lend in the area. Moreover, local whites pursued similar efforts on the municipal level, passing racial segregation ordinances in 1913, 1916, 1929, and 1931 - despite Supreme Court rulings in 1917 and 1924 that such laws were unconstitutional.  Even though these particular attempts failed, it demonstrates how determined whites were to keep African Americans out of “their” neighborhoods.",
        "itemMedia":'<img class="content" src="images/04.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/04.jpg">',
        "mediaType" : "image",
    },
    {
    	"itemName": " Fire in the Old Fourth Ward",
    	"itemSubhead": "1917 Great Atlanta Fire",
        "itemDescription": "In 1917 The Great Atlanta Fire destroyed many homes on Auburn Avenue and in the 4th Ward, where most Black families lived up until then. This caused mass migration of Black families to the city’s Westside, one of the few areas in Atlanta where whites did not vigorously oppose Black settlement. Many Black families moved to Vine City and nearby areas.",
    	"itemMedia":'<img class="content" src="images/03.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/03.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Public Housing Developments Displace Residents",
        "itemSubhead": "Supposed “Slums” Demolished to Make Way for New Developments",
        "itemDescription": "Thousands of Black residents were displaced when the Atlanta Housing Authority started building public housing in the mid-1930s. As in virtually all American cities at the time, these housing projects were racially segregated, formally in the South but informally in the North prior to 1964.  Not all of the housing destroyed fit the description of “slums” that was used to justify these projects. This man, moving his family’s belongings prior to the opening of the Alonzo Herndon Homes in 1941, may have hauled ice for a living, small-scale entrepreneurship being a strategy some Black men successfully used to avoid racial discrimination in the workplace.  Black homeowners in the demolished areas typically did not receive fair market value for their homes, and faced the predicament of finding new housing in a segregated market with many areas off-limits to them.",
        "itemMedia":'<img class="content" src="images/05.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/05.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Life on the Westside in the 1950's",
        "itemSubhead": "Myrtle Dansby, English Avenue Resident, Remembers the Neighborhood",
        "itemDescription": "Myrtle Dansby was one of the many Old Fourth Ward residents who moved to the Westside in the 1940’s. She has lived in the area for the last sixty-six years and recalls fond memories of the neighborhood in the 1950’s and 1960’s.",
        "itemMedia":'https://player.vimeo.com/video/134208479?title=0&byline=0&portrait=0?api=1',
        "itemThumb" : '<img class="content" src="thumbs/video01.jpg">',
        "mediaType" : "video",
    },
    {
        "itemName": "Changing Demographics",
        "itemSubhead": "Affordable Housing on the Westside: 1940's - 1960's",
        "itemDescription": "By 1930 Vine City and most of the Westside was majority-Black. Exceptions did exist – working class white families continued to live in the area through the 1940’s, especially in “Bellwood” (present day English Avenue) – but as increasing numbers of Black families moved to the area in the 1940's and 1950's, when all Black housing projects were built, white families continued to move out.",
        "itemMedia":'<img class="content" src="images/06.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/06.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "The Development Train",
        "itemSubhead": "The Development Train",
        "itemDescription": "During the 1960’s and 70’s a burst of suburban malls were built as more and more whites and affluent Black Atlantans moved to the suburbs. At the same time Atlanta’s white business elite worked hard to shape the city; hotels and gleaming office towers cropped up all over the northern edge and in 1966 Atlanta became the first city to have two professional sports teams when the Milwaukee Braves moved to Atlanta. These business leaders envisioned a downtown constructed primarily for business conventions and worked with conservative state leaders to secure funding for the state-owned Georgia World Congress Center, which opened in 1976. Yet in 1973 the city also elected its first black mayor, Maynard Jackson. Many credit this delicate balance between Black and white business and political leaders with earlier city leaders’ pro-business approach to quieting racial unrest through compromise and back room deals. Whatever the behind the door tensions, the development train rarely slowed down during this time period. As the picture here illustrates, in the mid-1970’s the MARTA public transportation system was built, connecting the Westside communities more directly to downtown Atlanta, but not providing a comprehensive transit network that could have enabled access to the northern metro area where the most job growth was taking place.",
        "itemMedia":'<img class="content" src="images/12.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/12.jpg">',
        "mediaType" : "audio",
    },
    {
        "itemName": "“Delaying Conveniences” in the 1950’s",
        "itemSubhead": "Tilman Ward Discusses not having Hot Water or Television",
        "itemDescription": "Tilman Ward, interviewed here, grew up in Vine City right on the site of the present day Ashby Street Marta station. Tilman’s father taught himself how to build without any formal education and built the duplex that he and his family lived in. They rented out one side and used the rental income to send their children to college. This sort of dogged approach to earning a living and saving money so that future generations would benefit was a common experience in the neighborhood in the 1950’s and 60’s, and was a strategy used by many African American families to create housing that white developers were often unwilling to build.  Black owner-builders commonly saved money to buy vacant land, then gradually built their own houses as they could afford, with some even re-using salvaged lumber in order to economize, and often foregoing amenities like electricity in the meantime.  When owners could not complete the work themselves, they typically turned to Black building tradesmen like carpenters and masons, keeping economic gains within communities.",
        "itemMedia":'https://player.vimeo.com/video/132671367?portrait=0',
        "itemThumb" : '<img class="content" src="thumbs/video02.jpg">',
        "mediaType" : "video",
    },
    {
        "itemName": "Martin Luther King Jr. Leads Demonstrations for Fair Housing in Vine City",
        "itemSubhead": "1960's Rising Tensions over Racial Discrimination Result in Protests",
        "itemDescription": "In the 1960’s issues over racial discrimination across housing, services and infrastructure erupted in protests. Common issues facing Black families included: overpaying for sub-standard housing; absentee landlords ignoring tenants’ requests; lack of access to affordable and high quality food; and laws, policies and social practices that forced Black families into the least desirable, low-lying parts of the city where poor drainage and sanitation problems were prevalent. Moreover, in Atlanta, the city refused to pave streets in Black neighborhoods into the 1950s and in the early twentieth century, even refused to pick up garbage. In 1966 Martin Luther King Jr. and Coretta Scott, who, in 1965 had moved into a home at 239 Sunset Avenue in Vine City, led a protest in the neighborhood against the unsafe and unfair housing conditions.",
        "itemMedia":'<img class="content" src="images/07.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/07.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Political Maneuverings",
        "itemSubhead": "July, 1988: State, County and City Embroiled in Arguments about the Terms of the Dome",
        "itemDescription": "The first Georgia Dome deal was spearheaded by a group of investors, the “Stadium Corporation,” with support from the board of the Georgia World Congress Center. While the Dome was ultimately built on what the state considered “abandoned railroad land” the expansion of the World Congress Center, which was wrapped up in the deal, included the use of eminent domain to seize and raze 126 homes in the Lightning Community and relocate those families. The community was outraged, so were the churches. Prominent members of city council also spoke up against the early plans. In response, the Stadium Corporation, the city and the county promised to help set up a ten million dollar trust fund to help build affordable housing in the area. Many were still upset about the agreement but plans proceeded. The state, city and county all had roles to play and approval votes had to come from all three governing bodies. However, in interviews like this one, with then Fulton County Commissioner Nancy Boxill, the emphasis is on the state’s role in the stadium deal. The financing for the estimated $158 million needed to build the Dome required that 1/3 of the cost come from the city and county hotel-motel tax.",
        "itemMedia":'<div class="audioContainer"><audio controls><source src="images/audio2.mp3" type="audio/mpeg">Your browser does not support the audio element.</audio></div>',
        "itemThumb" : '<img class="content" src="thumbs/placeholder.jpg">',
        "mediaType" : "audio",
    },
    {
        "itemName": "Ivory Young Discusses the “Taking” of Lightning",
        "itemSubhead": "Looking Back on What Happened to Lightning",
        "itemDescription": "In 2015 Councilmen Young was interviewed about his memory of the negotiations over the 1992 Georgia Dome. Councilman Young worked for the architectural and construction firm that designed and managed the construction of the 150 homes that were to be built using the ten million dollar trust fund. He looks back on the way that the 1992 Dome negotiation took place, reflecting with dismay over the injustice of what happened to the community of Lightning.",
        "itemMedia":'https://player.vimeo.com/video/145779833?portrait=0',
        "itemThumb" : '<img class="content" src="thumbs/18.jpg">',
        "mediaType" : "video",
    },
    {
        "itemName": "Work Begins on Affordable Housing in Vine City",
        "itemSubhead": "By 1990 Work Had Begun on Affordable Housing Units Tied to Stadium Agreement",
        "itemDescription": "In May of 1990, groundbreaking for the 150 planned single-family houses in Vine City began. Ultimately, most of the funding for the trust fund came from the city and the county, with two million dollars promised from private funds to be raised by the Stadium Corporation. While the homes were relatively affordable, homeowners had to qualify for the $55,000 mortgage and have an income of about $17,000 a year. Plans were to complete construction of the houses over the next 3 years and as this picture shows construction began immediately. ",
        "itemMedia":'<img class="content" src="images/19.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/19.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Selling 150 Affordable Housing Units Proves Difficult",
        "itemSubhead": "Housing Ministry Finding Few Who Qualify for Low-Price Homes",
        "itemDescription": "Optimism about the 150 affordable units started to wane by October 1990 when the 11 churches working together under the Vine City Housing Ministry reported that they had only been able to sell 1 of the 5 houses constructed. Much of this had to do with the relative poverty of neighborhood residents and the fact that even “affordable” housing was out of reach for them. As the Atlanta Journal Constitution reported: “Of the 400 applications distributed, 300 were returned but only 1 qualified.” The problems were also tied to market logic. Trying to sell new houses that cost $40,000 - $60,000 right next to vacant lots or old homes that had been sitting empty for decades proved a challenge, as this photograph shows.",
        "itemMedia":'<img class="content" src="images/20.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/20.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Disputing the Blame Placed on the Vine City Housing Ministry",
        "itemSubhead": "In a 2015 Interview Cottrell Disputes Claims that Housing Ministry was at Fault",
        "itemDescription": "The October 1990 problems with building housing were only a small indication of the troubles to come. The Vine City Housing Ministry not only faced challenges selling and financing the houses, but since they did not have expertise in the building trades, they also had trouble managing their role as community developers. Meanwhile, city, state and county officials and the various investors in the project also played roles: advising the ministry, selecting developers and checking in on their progress. The historical record shows a complex web of decision-making. Moreover, structural factors, such as racist lending policies, metropolitan expansion and the departure of more fortunate residents from Vine City, made selling land in the area difficult. However, the contemporary story about what happened places most of the blame on the churches and community developers. In this recent interview, Reverend Cottrell goes back to his memories of the 1990’s and challenges the media interpretation that failure was entirely the fault of the ministry.",
        "itemMedia":'https://player.vimeo.com/video/145780308?portrait=0',
        "itemThumb" : '<img class="content" src="thumbs/video04.jpg">',
        "mediaType" : "video",
    },
    {
        "itemName": "The Color of Money",
        "itemSubhead": "The Atlanta Journal Constitution’s Exposes Widespread Racist Lending Practices in 1989 Series",
        "itemDescription": "Another challenge faced by the Vine City Housing Ministry that the media did not discuss was the practice of racist lending policies, prevalent from the late 1980’s and into the early 1990’s. In 1989 the Atlanta Journal Constitution ran a Pulitzer Prize winning series called The Color of Money, which investigated the impact of race on lending practices in the city of Atlanta. The report uncovered sad truths about lending practices and put into context the severe economic and social challenges facing Black families in the city. As the maps here show, the Westside communities were at the heart of this structural problem.",
        "itemMedia":'<img class="content" src="images/22.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/22.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Demolition of Public Housing in Atlanta",
        "itemSubhead": "Starting in 1994 the Atlanta Housing Authority began demolishing public housing projects",
        "itemDescription": "Based on the perception that public housing was a failure, and fueled by funds from the U.S. Department of Housing and Urban Development's Hope VI, the Atlanta Housing Authority adopted a plan to replace low-income public housing projects with mixed income communities.  The Housing Authority received the first pilot grant in 1993.  Begun in 1994, the demolition continued through 2011.  While there have been some successes with the model of mixed income communities, Deirdre Oakley, assistant professor at Georgia State, has done a study that suggests that many residents have been relocated to neighborhoods that are not significantly better than those they left and most of the housing is from the private rental market which does not guarantee availability to low income residents.",
        "itemMedia":'<img class="content" src="images/23.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/23.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Under Water: A Flood, Tornado and the 2007 Foreclosure Crisis",
        "itemSubhead": "1997-2008: Hardship on the Westside",
        "itemDescription": "After the excitement of the 1996 Olympics receded, residents of the Westside noticed little economic benefit from the influx of money that came in during the surge of development. Instead, by 2001 another jobs recession was hurting an area already plagued by unemployment and poverty and the housing boom was spurring investment but little change. When the 2007 Great Recession hit and the housing bubble burst, more buildings and houses were left empty, homeowners were underwater on mortgages (many of them given under fraudulent conditions) and renters were being evicted from homes owned by absentee landlords. A 2002 flood and an outdated sewer system put parts of the Westside 6 feet under water and a 2008 tornado again ravaged the neighborhood.",
        "itemMedia":'<img class="content" src="images/placeholder.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/placeholder.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Foreclosure Crisis and Occupy our Homes in Vine City ",
        "itemSubhead": "New Pockets of Activism and Resistance",
        "itemDescription": "The foreclosure crisis hit this country hard. Between 2007 and today, more than 5 million American households have experienced foreclosure. This waterfall of foreclosures most adversely impacted working and middle class Americans, particularly Americans of color. And a number of the mortgages and evictions were fraudulent. With fraud also came resistance and activism. Atlanta’s Occupy Our Homes emerged from the Occupy and housing justice movements to help working class Atlantans fight for the right to fair housing. In 2012 the group helped the Higher Ground Empowerment Center, a historic church in Vine City and a homeowner, fight to stay in their homes. Part of the post-Occupy resurgence of direct action activism, Occupy Our Homes activity shows that new pockets of activism can crop up and shift the landscape of community response, even if only momentarily. ",
        "itemMedia":'<img class="content" src="images/24.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/24.jpg">',
        "mediaType" : "image",
    },
    {
        "itemName": "Two line name, 30 characters",
        "itemSubhead": "Two line subhead, 37 characters limit",
        "itemDescription": "Description can be much longer, but should be limited to 260 characters... Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
        "itemMedia":'<img class="content" src="images/placeholder.jpg">',
        "itemThumb" : '<img class="content" src="thumbs/placerholder.jpg">',
        "mediaType" : "image",
    },

]